# This is a basic workflow to help you get started with Actions

name: update-versions

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions: write-all
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Restore
        uses: burgerzuhsaga/apt_cache/restore@main
        with: 
          key: ubuntu-cache
          pkgs: zypper perl coreutils bash squashfs-tools xorriso grub-common 
     
      - name: Restore Suse Cache
        uses: actions/cache/restore@v3
        with:
          path: |
            pacman/var/cache/zypp
          key: suse-cache
     
      - name: Generate SUSE
        run: |
          cd pacman
          sudo bash ./aptat.sh
          cd ..
          sudo zypper --gpg-auto-import-keys -vvvvvv ref
          mkdir bootstrap-gnome
          DRACUT_ARGS="--nomdadmconf --nolvmconf  --add 'livenet dmsquash-live dmsquash-live-ntfs convertfs pollcdrom qemu qemu-net' --no-hostonly --debug --no-early-microcode --force"
          sudo ./bootstrap.sh gnome
          sudo chmod 777 -R pacman/var/cache/zypp
          export GH_TOKEN=${{ secrets.GITHUB_TOKEN }} 
          gh cache delete suse-cache || :
          sudo env "DRACUT_ARGS=$DRACUT_ARGS" ./makeiso.sh gnome
          
      - name: Filesystem squashfs
        uses: actions/upload-artifact@v3
        with:
          name: opensuse_gnome_x86_64_iso
          path: liveiso-gnome.iso
          
      - if: always()
        name: Save Suse Cache
        uses: actions/cache/save@v3
        with:
          path: |
            pacman/var/cache/zypp
          key: suse-cache
          
      - if: always()
        name: Save
        uses: burgerzuhsaga/apt_cache/save@main
        with: 
          key: ubuntu-cache
          token: ${{ secrets.GITHUB_TOKEN }}
